export const PATIENT_LOGIN = "PATIENT_LOGIN";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_USER_INSURANCE = "SET_CURRENT_USER_INSURANCE";
export const GET_ERRORS = "GET_ERRORS";
export const GET_MEDICAL_RECORD = "GET_MEDICAL_RECORD";
export const GET_PATIENT_INFORMATION_WITH_ID = "GET_PATIENT_INFORMATION_WITH_ID";
export const SELECTED_RECORD_ID = "SELECTED_RECORD_ID";
export const GET_MEDICAL_RECORD_WITH_ID = "GET_MEDICAL_RECORD_WITH_ID";
